#####

#https://bybel.org/pwl/genesis/1.htm

df_lang = { 
            "Afrikaans":"https://bybel.org/pwl/"
            "Albanian":"https://biblehub.com/alb/"
            "Amharic NT":"https://biblehub.com/amh/"
            "Aramaic NT":"https://biblehub.com/pes/"
            "Arabic":"https://biblehub.com/arb/"
            "Armenian NT":"https://biblehub.com/arm/"
            "Basque NT":"https://biblehub.com/bas/"
            "Brazilian Portuguese":"https://bibliaportugues.com/kja/"
            "Bulgarian":"https://biblehub.com/bul/"
            "Chinese":"https://holybible.com.cn/"
            "Croatian":"https://biblehub.com/cro/"
            "Czech":"https://biblehub.com/bkr/"
            "Danish":"https://da.bibelsite.com/dan/"
            "Dutch":"https://biblehub.com/svg/"
            "Hungarian":"https://biblehub.com/hun/"
            "English":"https://biblehub.com/niv/"
            "Esperanto":"https://biblehub.com/esp/"
            "Estonian NT":"https://biblehub.com/est/"
            "Finnish":"https://biblehub.com/pr38/"
            "French":"https://saintebible.com/mar/"
            "German":"https://bibeltext.com/l12/"
            "Greek":"https://biblehub.com/sepd/"
            "Haitian Creole":"https://biblehub.com/hcb/"
            "Italian":"https://biblehub.com/rb/"
            "Indonesian":"https://biblehub.com/tb/"
            "Japanese NT":"https://biblehub.com/jpn/"
            "Kabyle NT":"https://biblehub.com/kab/"
            "Korean":"https://biblehub.com/kor/"
            "Latin":"https://biblehub.com/vul/"
            "Latvian NT":"https://biblehub.com/lat/"
            "Lithuanian":"https://biblehub.com/lit/"
            "Maori":"https://biblehub.com/mao/"
            "Norwegian":"https://no.bibelsite.com/nor/"
            "Polish":"https://biblehub.com/pol/"
            "Portuguese":"https://bibliaportugues.com/jfa/"
            "Romanian":"https://biblehub.com/rom/"
            "Russian":"https://biblehub.com/st/"
            "Shuar NT":"https://biblehub.com/shu/"
            "Spanish":"https://bibliaparalela.com/lbla/"
            "Swahili NT":"https://biblehub.com/swa/"
            "Swedish":"https://sv.bibelsite.com/swe/"
            "Tagalog":"https://biblehub.com/adb/"
            "Tawallamat Tamajaq NT":"https://biblehub.com/ttq/"
            "Thai":"https://biblehub.com/tha/"
            "Turkish":"https://biblehub.com/tur/"
            "Ukrainian NT":"https://biblehub.com/ukr/"
            "Uma NT":"https://biblehub.com/uma/"
            "Vietnamese":"https://biblehub.com/vie/"
}

#If NT in name, then Matthew index ++ only. 